#pragma once

static const char DASHBOARD_HTML[] =
"<!DOCTYPE html>"
"<html lang=\"en\">"
"<head>"
"<meta charset=\"UTF-8\">"
"<meta name=\"viewport\" content=\"width=device-width,initial-scale=1\">"
"<title>Wi-Fi CSI Presence Radar</title>"
"<style>"
":root{"
"--bg:#081018;"
"--panel:#102233;"
"--panel-alt:#152b40;"
"--line:#24415c;"
"--text:#eef6ff;"
"--muted:#8ea7bf;"
"--good:#4ce5a6;"
"--warn:#ffd166;"
"--hot:#ff6b6b;"
"--cold:#57c7ff;"
"--mono:ui-monospace,SFMono-Regular,Menlo,Consolas,monospace;"
"}"
"*{box-sizing:border-box}"
"body{margin:0;font-family:var(--mono);background:radial-gradient(circle at top,#16324a 0%,#081018 55%);color:var(--text);min-height:100vh}"
".shell{max-width:1200px;margin:0 auto;padding:24px 18px 48px}"
".hero{display:grid;grid-template-columns:1.4fr .9fr;gap:18px;align-items:stretch}"
".panel{background:linear-gradient(180deg,rgba(21,43,64,.92),rgba(10,22,34,.92));border:1px solid var(--line);border-radius:20px;box-shadow:0 16px 50px rgba(0,0,0,.28)}"
".hero-main{padding:24px}"
".eyebrow{font-size:12px;letter-spacing:.28em;text-transform:uppercase;color:var(--cold)}"
"h1{margin:10px 0 16px;font-size:34px;line-height:1.1}"
".status-row{display:flex;flex-wrap:wrap;gap:12px;align-items:center}"
".pill{display:inline-flex;align-items:center;gap:10px;padding:10px 14px;border-radius:999px;font-size:13px;letter-spacing:.08em;text-transform:uppercase;background:rgba(87,199,255,.08);border:1px solid rgba(87,199,255,.2)}"
".dot{width:10px;height:10px;border-radius:50%;background:var(--muted)}"
".pill.no_presence .dot{background:var(--good);box-shadow:0 0 18px var(--good)}"
".pill.presence_static .dot{background:var(--cold);box-shadow:0 0 18px var(--cold)}"
".pill.presence_motion .dot{background:var(--hot);box-shadow:0 0 18px var(--hot)}"
".quality-poor{color:var(--hot)}.quality-fair{color:var(--warn)}.quality-good,.quality-excellent{color:var(--good)}"
".hero-copy{margin-top:16px;color:var(--muted);line-height:1.7;font-size:14px}"
".hero-side{padding:22px;display:grid;gap:14px}"
".side-card{padding:14px 16px;border-radius:16px;background:rgba(8,16,24,.38);border:1px solid rgba(142,167,191,.15)}"
".side-label{font-size:11px;letter-spacing:.22em;text-transform:uppercase;color:var(--muted)}"
".side-value{margin-top:8px;font-size:24px;font-weight:700}"
".grid{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:14px;margin-top:18px}"
".metric{padding:16px;border-radius:18px;background:rgba(8,16,24,.36);border:1px solid rgba(142,167,191,.12)}"
".metric .label{font-size:11px;letter-spacing:.22em;text-transform:uppercase;color:var(--muted)}"
".metric .value{margin-top:10px;font-size:26px;font-weight:700}"
".metric .hint{margin-top:6px;font-size:12px;color:var(--muted)}"
".layout{display:grid;grid-template-columns:1.25fr .75fr;gap:18px;margin-top:18px}"
".canvas-panel{padding:20px}"
".canvas-head{display:flex;justify-content:space-between;gap:12px;align-items:flex-end;margin-bottom:14px}"
".title{font-size:13px;letter-spacing:.24em;text-transform:uppercase;color:var(--cold)}"
".subtitle{font-size:12px;color:var(--muted);margin-top:6px}"
"canvas{width:100%;display:block;border-radius:16px;background:linear-gradient(180deg,rgba(6,14,22,.92),rgba(9,18,28,.92));border:1px solid rgba(142,167,191,.12)}"
"#wave{height:240px}"
".viz-stack{display:grid;gap:18px}"
"#waterfall{height:280px}"
".legend{display:flex;justify-content:space-between;gap:10px;align-items:center;margin-top:10px;color:var(--muted);font-size:11px;letter-spacing:.08em;text-transform:uppercase}"
".legend-bar{flex:1;height:8px;border-radius:999px;background:linear-gradient(90deg,#06111c 0%,#0b4f6c 24%,#24c1ff 48%,#ffd166 72%,#ff6b6b 100%);border:1px solid rgba(142,167,191,.16)}"
".controls{padding:20px;display:grid;gap:16px}"
".control{display:grid;gap:8px}"
".control label{font-size:12px;letter-spacing:.14em;text-transform:uppercase;color:var(--muted)}"
".check-row{display:flex;align-items:center;gap:10px;font-size:12px;color:var(--muted)}"
".check-row input{accent-color:var(--warn)}"
".range-row{display:flex;gap:12px;align-items:center}"
"input[type=range]{width:100%}"
".mini{font-size:12px;color:var(--muted)}"
".tag-row{display:grid;gap:8px}"
".tag-buttons{display:flex;gap:8px;flex-wrap:wrap}"
".tag-btn{padding:10px 12px;font-size:12px}"
".btns{display:flex;gap:10px;flex-wrap:wrap}"
".btns.compact button{padding:10px 14px}"
"button{border:none;border-radius:14px;padding:12px 16px;font-family:var(--mono);font-size:13px;cursor:pointer}"
"button:disabled{opacity:.45;cursor:not-allowed}"
".primary{background:var(--cold);color:#04111c}"
".secondary{background:rgba(87,199,255,.12);color:var(--text);border:1px solid rgba(87,199,255,.18)}"
".toggle-on{background:rgba(76,229,166,.14);border:1px solid rgba(76,229,166,.3);color:var(--text)}"
".toggle-off{background:rgba(255,107,107,.14);border:1px solid rgba(255,107,107,.25);color:var(--text)}"
".log{margin-top:18px;padding:20px}"
".log-list{margin:0;padding:0;list-style:none;display:grid;gap:10px}"
".log-item{padding:12px 14px;border-radius:14px;background:rgba(8,16,24,.34);border:1px solid rgba(142,167,191,.1);font-size:13px;line-height:1.5}"
".diag{margin-top:18px;padding:20px}"
".diag-grid{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:10px;margin-top:14px}"
".diag-item{padding:12px;border-radius:14px;background:rgba(8,16,24,.34);border:1px solid rgba(142,167,191,.1)}"
".diag-k{font-size:11px;letter-spacing:.18em;text-transform:uppercase;color:var(--muted)}"
".diag-v{margin-top:8px;font-size:18px;font-weight:700;line-height:1.3}"
".diag-note{margin-top:12px;color:var(--muted);font-size:13px;line-height:1.6}"
".foot{display:flex;justify-content:space-between;gap:10px;flex-wrap:wrap;margin-top:18px;color:var(--muted);font-size:12px}"
"@media (max-width:960px){.hero,.layout{grid-template-columns:1fr}.grid,.diag-grid{grid-template-columns:repeat(2,minmax(0,1fr))}}"
"@media (max-width:620px){.grid,.diag-grid{grid-template-columns:1fr}h1{font-size:28px}}"
"</style>"
"</head>"
"<body>"
"<div class=\"shell\">"
"<section class=\"hero\">"
"<div class=\"panel hero-main\">"
"<div class=\"eyebrow\">ESP32 CSI Radar</div>"
"<h1>Realtime three-state Wi-Fi presence sensing</h1>"
"<div class=\"status-row\">"
"<div id=\"state-pill\" class=\"pill no_presence\"><span class=\"dot\"></span><span id=\"state-text\">no_presence</span></div>"
"<div class=\"pill\"><span>Role</span><strong id=\"role-text\">sensor_sta</strong></div>"
"<div class=\"pill\"><span>Wi-Fi</span><strong id=\"wifi-text\">connecting</strong></div>"
"<div class=\"pill\"><span>Calibration</span><strong id=\"cal-text\">0%</strong></div>"
"<div class=\"pill\"><span>RSSI</span><strong id=\"rssi-text\">-- dBm</strong></div>"
"<div class=\"pill\"><span>Detection</span><strong id=\"detect-text\">paused</strong></div>"
"</div>"
"<div class=\"hero-copy\">"
"Presence starts with robust empty-room rejection, then separates still presence from motion using drift-aware CSI scores. Use the browser for lightweight viewing, serial for quick debugging, and the dedicated <code>/ws/log</code> stream for full-rate host capture."
"</div>"
"</div>"
"<aside class=\"panel hero-side\">"
"<div class=\"side-card\"><div class=\"side-label\">Device</div><div class=\"side-value\" id=\"ip-text\">0.0.0.0</div></div>"
"<div class=\"side-card\"><div class=\"side-label\">AP Clients</div><div class=\"side-value\" id=\"client-text\">0</div></div>"
"<div class=\"side-card\"><div class=\"side-label\">Presence Events</div><div class=\"side-value\" id=\"event-text\">0</div></div>"
"<div class=\"side-card\"><div class=\"side-label\">Disturbance Alerts</div><div class=\"side-value\" id=\"disturbance-text\">0</div></div>"
"<div class=\"side-card\"><div class=\"side-label\">Setup Quality</div><div class=\"side-value\" id=\"quality-text\">--</div></div>"
"</aside>"
"</section>"
"<section class=\"grid\">"
"<div class=\"metric panel\"><div class=\"label\">Occupancy Score</div><div class=\"value\" id=\"occ-text\">0.00</div><div class=\"hint\">Empty-room deviation</div></div>"
"<div class=\"metric panel\"><div class=\"label\">Motion Score</div><div class=\"value\" id=\"motion-text\">0.00</div><div class=\"hint\">Macro motion energy</div></div>"
"<div class=\"metric panel\"><div class=\"label\">Stability Score</div><div class=\"value\" id=\"stability-text\">0.00</div><div class=\"hint\">Higher means mostly static</div></div>"
"</section>"
"<section class=\"layout\">"
"<div class=\"panel canvas-panel\">"
"<div class=\"viz-stack\">"
"<div>"
"<div class=\"canvas-head\"><div><div class=\"title\">CSI Amplitude Envelope</div><div class=\"subtitle\">Live subcarrier amplitude preview</div></div><div class=\"mini\" id=\"subcarrier-text\">0 active subcarriers</div></div>"
"<canvas id=\"wave\" width=\"860\" height=\"240\"></canvas>"
"</div>"
"<div>"
"<div class=\"canvas-head\"><div><div class=\"title\">CSI Waterfall Heatmap</div><div class=\"subtitle\">Rolling time history of subcarrier change intensity</div></div><div class=\"mini\" id=\"waterfall-text\">time → newest on right</div></div>"
"<canvas id=\"waterfall\" width=\"860\" height=\"280\"></canvas>"
"<div class=\"legend\"><span>Calm</span><div class=\"legend-bar\"></div><span>Active</span></div>"
"</div>"
"</div>"
"</div>"
"<div class=\"panel controls\">"
"<div class=\"btns compact\"><button class=\"secondary\" id=\"tune-lock-btn\">Unlock Tuning</button></div>"
"<div class=\"control\"><label for=\"motion-range\">Motion Threshold</label><div class=\"range-row\"><input id=\"motion-range\" type=\"range\" min=\"1.0\" max=\"4.0\" step=\"0.05\" value=\"1.35\"><span id=\"motion-range-text\">1.35</span></div><div class=\"mini\">Raise to reduce false triggers, lower to react sooner.</div></div>"
"<div class=\"control\"><label for=\"motion-clear-range\">Motion Clear</label><div class=\"range-row\"><input id=\"motion-clear-range\" data-profile-threshold=\"motion_clear\" type=\"range\" min=\"0.4\" max=\"4.0\" step=\"0.05\" value=\"1.05\"><span id=\"motion-clear-range-text\">1.05</span></div></div>"
"<div class=\"control\"><label for=\"presence-enter-range\">Presence Enter</label><div class=\"range-row\"><input id=\"presence-enter-range\" data-profile-threshold=\"presence_enter\" type=\"range\" min=\"0.6\" max=\"6.0\" step=\"0.05\" value=\"0.98\"><span id=\"presence-enter-range-text\">0.98</span></div></div>"
"<div class=\"control\"><label for=\"presence-clear-range\">Presence Clear</label><div class=\"range-row\"><input id=\"presence-clear-range\" data-profile-threshold=\"presence_clear\" type=\"range\" min=\"0.4\" max=\"6.0\" step=\"0.05\" value=\"0.82\"><span id=\"presence-clear-range-text\">0.82</span></div><div class=\"mini\">Unlock tuning to override the active profile.</div></div>"
"<div class=\"control\"><label for=\"notch-range\">Notch Filter (Hz)</label><div class=\"range-row\"><input id=\"notch-range\" type=\"range\" min=\"0\" max=\"22.5\" step=\"0.1\" value=\"0.0\"><span id=\"notch-range-text\">0.0</span></div><div class=\"mini\">Use for periodic disturbances such as fans.</div></div>"
"<div class=\"tag-row\"><div class=\"mini\">Manual annotation: <span id=\"annotation-text\">none</span></div><div class=\"tag-buttons\"><button class=\"secondary tag-btn\" data-annotation=\"none\">Clear</button><button class=\"secondary tag-btn\" data-annotation=\"no_presence\">No Presence</button><button class=\"secondary tag-btn\" data-annotation=\"presence_static\">Static</button><button class=\"secondary tag-btn\" data-annotation=\"presence_motion\">Motion</button></div></div>"
"<label class=\"check-row\"><input id=\"force-calibration\" type=\"checkbox\"><span>Force calibration even if someone is in the sensing area</span></label>"
"<div class=\"btns\">"
"<button class=\"primary\" id=\"detect-btn\">Start Detection</button>"
"<button class=\"primary\" id=\"recal-btn\">Recalibrate Empty Room</button>"
"<button class=\"secondary\" id=\"logging-btn\">Serial Logging (debug): off</button>"
"<button class=\"secondary\" id=\"capture-btn\">Start Browser Capture (light)</button>"
"</div>"
"<div class=\"mini\">Local WS Logger (recommended): <code id=\"ws-log-command\">node tools/capture_ws.mjs ws://device-ip/ws/log session.csv</code></div>"
"<div class=\"mini\">Log stream clients: <span id=\"log-client-text\">0</span></div>"
"<div class=\"mini\">Last packet timestamp: <span id=\"ts-text\">0</span> us</div>"
"<div class=\"mini\">Baseline ready: <span id=\"baseline-text\">no</span></div>"
"<div class=\"mini\">Calibration guard: <span id=\"cal-guard-text\">clear</span> • blocks <span id=\"cal-guard-count\">0</span></div>"
"<div class=\"mini\">Browser capture (light): <span id=\"capture-status\">idle</span> • rows <span id=\"capture-count\">0</span></div>"
"</div>"
"</section>"
"<section class=\"panel diag\">"
"<div class=\"title\">Guided Setup</div>"
"<div class=\"diag-note\" id=\"setup-step\">Start detection with an empty sensing area.</div>"
"<div class=\"btns\" style=\"margin-top:14px\"><button class=\"primary\" id=\"guided-start-btn\">Start Guided Setup</button><button class=\"secondary\" id=\"guided-sample-btn\">Start Sampling</button><button class=\"secondary\" id=\"guided-next-btn\">Next Step</button><button class=\"secondary\" id=\"guided-apply-btn\">Apply Suggested Profile</button><button class=\"secondary\" id=\"guided-cancel-btn\">Cancel Setup</button></div>"
"<div class=\"diag-grid\">"
"<div class=\"diag-item\"><div class=\"diag-k\">Deployment</div><div class=\"diag-v\" id=\"deploy-text\">not ready</div></div>"
"<div class=\"diag-item\"><div class=\"diag-k\">Quality Score</div><div class=\"diag-v\" id=\"quality-score-text\">0 / 100</div></div>"
"<div class=\"diag-item\"><div class=\"diag-k\">Primary Limiter</div><div class=\"diag-v\" id=\"quality-reason-text\">waiting</div></div>"
"<div class=\"diag-item\"><div class=\"diag-k\">RSSI Avg / Range</div><div class=\"diag-v\" id=\"diag-rssi\">--</div></div>"
"<div class=\"diag-item\"><div class=\"diag-k\">Setup Stage</div><div class=\"diag-v\" id=\"guided-stage-text\">idle</div></div>"
"<div class=\"diag-item\"><div class=\"diag-k\">Sampling State</div><div class=\"diag-v\" id=\"guided-sampling-text\">idle</div></div>"
"<div class=\"diag-item\"><div class=\"diag-k\">Stage Samples</div><div class=\"diag-v\" id=\"guided-samples-text\">0</div></div>"
"<div class=\"diag-item\"><div class=\"diag-k\">Setup Result</div><div class=\"diag-v\" id=\"guided-result-text\">incomplete</div></div>"
"<div class=\"diag-item\"><div class=\"diag-k\">Profile Mode</div><div class=\"diag-v\" id=\"guided-profile-mode-text\">incomplete</div></div>"
"<div class=\"diag-item\"><div class=\"diag-k\">Suggested Motion</div><div class=\"diag-v\" id=\"guided-motion-th-text\">0.00</div></div>"
"<div class=\"diag-item\"><div class=\"diag-k\">Suggested Presence</div><div class=\"diag-v\" id=\"guided-presence-th-text\">0.00</div></div>"
"<div class=\"diag-item\"><div class=\"diag-k\">Motion / Static Contrast</div><div class=\"diag-v\" id=\"guided-contrast-text\">0.00 / 0.00</div></div>"
"<div class=\"diag-item\"><div class=\"diag-k\">Walk Peak / Mean</div><div class=\"diag-v\" id=\"guided-walk-text\">0.00 / 0.00</div></div>"
"<div class=\"diag-item\"><div class=\"diag-k\">Still Occ / Motion</div><div class=\"diag-v\" id=\"guided-still-text\">0.00 / 0.00</div></div>"
"<div class=\"diag-item\"><div class=\"diag-k\">Clear Occ / Motion</div><div class=\"diag-v\" id=\"guided-clear-text\">0.00 / 0.00</div></div>"
"</div>"
"</section>"
"<section class=\"panel diag\">"
"<div class=\"title\">Diagnostics</div>"
"<div class=\"diag-note\" id=\"diag-verdict\">Waiting for enough CSI to diagnose.</div>"
"<div class=\"diag-grid\">"
"<div class=\"diag-item\"><div class=\"diag-k\">Packet Rate</div><div class=\"diag-v\" id=\"diag-rate\">0.00 Hz</div></div>"
"<div class=\"diag-item\"><div class=\"diag-k\">Packet Jitter</div><div class=\"diag-v\" id=\"diag-jitter\">0.00 Hz</div></div>"
"<div class=\"diag-item\"><div class=\"diag-k\">Subcarriers Used</div><div class=\"diag-v\" id=\"diag-sc\">0 / 0</div></div>"
"<div class=\"diag-item\"><div class=\"diag-k\">CSI Queue Drops</div><div class=\"diag-v\" id=\"diag-drops\">0</div></div>"
"<div class=\"diag-item\"><div class=\"diag-k\">Occupancy Energy / Ref</div><div class=\"diag-v\" id=\"diag-occ-raw\">0.00 / 0.00</div></div>"
"<div class=\"diag-item\"><div class=\"diag-k\">Motion Avg / Ref</div><div class=\"diag-v\" id=\"diag-motion-avg\">0.00 / 0.00</div></div>"
"<div class=\"diag-item\"><div class=\"diag-k\">Motion Energy / Enter</div><div class=\"diag-v\" id=\"diag-motion-raw\">0.00 / 0.00</div></div>"
"<div class=\"diag-item\"><div class=\"diag-k\">Presence Enter / Clear</div><div class=\"diag-v\" id=\"diag-presence-th\">0.00 / 0.00</div></div>"
"<div class=\"diag-item\"><div class=\"diag-k\">FSM Counters</div><div class=\"diag-v\" id=\"diag-fsm\">M0 s0 c0</div></div>"
"<div class=\"diag-item\"><div class=\"diag-k\">Hold Frames</div><div class=\"diag-v\" id=\"diag-hold\">0</div></div>"
"<div class=\"diag-item\"><div class=\"diag-k\">Processed Frames</div><div class=\"diag-v\" id=\"diag-frames\">0</div></div>"
"</div>"
"</section>"
"<section class=\"panel log\">"
"<div class=\"title\">State Log</div>"
"<ul class=\"log-list\" id=\"log-list\"></ul>"
"<div class=\"foot\"><span>Serial debug capture: <code>idf.py monitor | grep \"CSI_DATA\" &gt; session.csv</code></span><span id=\"legacy-text\">status: waiting</span></div>"
"</section>"
"</div>"
"<script>"
"const WS_URL='ws://'+location.hostname+'/ws';"
"const wave=document.getElementById('wave');"
"const ctx=wave.getContext('2d');"
"const waterfall=document.getElementById('waterfall');"
"const waterfallCtx=waterfall.getContext('2d');"
"const motionRange=document.getElementById('motion-range');"
"const notchRange=document.getElementById('notch-range');"
"const profileThresholdRanges=Array.from(document.querySelectorAll('[data-profile-threshold]'));"
"const forceCalibration=document.getElementById('force-calibration');"
"const tuneLockBtn=document.getElementById('tune-lock-btn');"
"const motionRangeText=document.getElementById('motion-range-text');"
"const notchRangeText=document.getElementById('notch-range-text');"
"const logList=document.getElementById('log-list');"
"const loggingBtn=document.getElementById('logging-btn');"
"const captureBtn=document.getElementById('capture-btn');"
"const detectBtn=document.getElementById('detect-btn');"
"const recalBtn=document.getElementById('recal-btn');"
"const guidedStartBtn=document.getElementById('guided-start-btn');"
"const guidedSampleBtn=document.getElementById('guided-sample-btn');"
"const guidedNextBtn=document.getElementById('guided-next-btn');"
"const guidedApplyBtn=document.getElementById('guided-apply-btn');"
"const guidedCancelBtn=document.getElementById('guided-cancel-btn');"
"const annotationButtons=Array.from(document.querySelectorAll('[data-annotation]'));"
"let ws=null;"
"let reconnectTimer=null;"
"let amps=[];"
"const WATERFALL_HISTORY=180;"
"const WATERFALL_SUBCARRIERS=64;"
"let waterfallFrames=[];"
"let previousWaterfallSample=[];"
"let currentState='no_presence';"
"let lastEventCount=-1;"
"function createCaptureWorker(){"
"const workerFn=()=>{"
"let rows=[];"
"self.onmessage=(event)=>{"
"const msg=event.data||{};"
"if(msg.type==='reset'){rows=[];self.postMessage({type:'count',count:0});return;}"
"if(msg.type==='append'){if(msg.csv){msg.csv.split('\\n').forEach((line)=>{if(line){rows.push(line);}});}self.postMessage({type:'count',count:rows.length});return;}"
"if(msg.type==='download'){self.postMessage({type:'download_ready',csv:rows.length?(rows.join('\\n')+'\\n'):''});}"
"};"
"};"
"const blob=new Blob(['('+workerFn.toString()+')()'],{type:'text/javascript'});"
"const url=URL.createObjectURL(blob);"
"const worker=new Worker(url);"
"return worker;"
"}"
"let captureWorker=createCaptureWorker();"
"let captureRowCount=0;"
"let captureActive=false;"
"let tuningUnlocked=false;"
"let tuningAutoLockTimer=null;"
"const TUNING_AUTOLOCK_MS=8000;"
"function fmt(n){return Number(n||0).toFixed(2);}"
"function setText(id,text){document.getElementById(id).textContent=text;}"
"captureWorker.onmessage=(event)=>{"
"const msg=event.data||{};"
"if(msg.type==='count'){captureRowCount=Number(msg.count||0);setText('capture-count',String(captureRowCount));return;}"
"if(msg.type==='download_ready'){"
"if(!msg.csv){addLog('no capture rows buffered');return;}"
"const blob=new Blob([msg.csv],{type:'text/csv;charset=utf-8'});"
"const url=URL.createObjectURL(blob);"
"const a=document.createElement('a');"
"a.href=url;"
"a.download='esp32_capture_'+Date.now()+'.csv';"
"document.body.appendChild(a);"
"a.click();"
"a.remove();"
"URL.revokeObjectURL(url);"
"}"
"};"
"function downloadCapture(){"
"if(!captureRowCount){addLog('no capture rows buffered');return;}"
"captureWorker.postMessage({type:'download'});"
"}"
"function updateCaptureUi(){"
"captureBtn.textContent=captureActive?'Stop Browser Capture & Download':'Start Browser Capture (light)';"
"captureBtn.className=captureActive?'toggle-on':'secondary';"
"setText('capture-status',captureActive?'capturing':'idle');"
"setText('capture-count',String(captureRowCount));"
"}"
"function updateDetectionUi(enabled){"
"detectBtn.textContent=enabled?'Stop Detection':'Start Detection';"
"detectBtn.className=enabled?'toggle-on':'primary';"
"setText('detect-text',enabled?'running':'paused');"
"}"
"function scheduleTuningAutoLock(){"
"clearTimeout(tuningAutoLockTimer);"
"if(!tuningUnlocked){return;}"
"tuningAutoLockTimer=setTimeout(()=>{tuningUnlocked=false;updateTuneUi();addLog('tuning controls locked');},TUNING_AUTOLOCK_MS);"
"}"
"function updateTuneUi(){"
"const locked=!tuningUnlocked;"
"motionRange.disabled=locked;"
"profileThresholdRanges.forEach((input)=>{input.disabled=locked;});"
"notchRange.disabled=locked;"
"tuneLockBtn.textContent=locked?'Unlock Tuning':'Lock Tuning';"
"tuneLockBtn.className=locked?'secondary':'toggle-on';"
"}"
"function updateAnnotationUi(value){"
"const current=value||'none';"
"setText('annotation-text',current);"
"annotationButtons.forEach((btn)=>{btn.className=(btn.dataset.annotation===current)?'toggle-on tag-btn':'secondary tag-btn';});"
"}"
"function updateRoleUi(role,clients){"
"const apMode=role==='dedicated_ap';"
"setText('role-text',role||'sensor_sta');"
"setText('client-text',String(clients||0));"
"if(apMode){tuningUnlocked=false;clearTimeout(tuningAutoLockTimer);}"
"updateTuneUi();"
"motionRange.disabled=apMode||motionRange.disabled;"
"profileThresholdRanges.forEach((input)=>{input.disabled=apMode||input.disabled;});"
"notchRange.disabled=apMode||notchRange.disabled;"
"tuneLockBtn.disabled=apMode;"
"annotationButtons.forEach((btn)=>{btn.disabled=apMode;});"
"forceCalibration.disabled=apMode;"
"detectBtn.disabled=apMode;"
"recalBtn.disabled=apMode;"
"loggingBtn.disabled=apMode;"
"captureBtn.disabled=apMode;"
"guidedStartBtn.disabled=apMode;"
"guidedSampleBtn.disabled=apMode||guidedSampleBtn.disabled;"
"guidedNextBtn.disabled=apMode||guidedNextBtn.disabled;"
"guidedApplyBtn.disabled=apMode||guidedApplyBtn.disabled;"
"guidedCancelBtn.disabled=apMode;"
"if(apMode){setText('detect-text','n/a');}"
"}"
"function handleCaptureRow(line){"
"if(!captureActive||!line){return;}"
"captureWorker.postMessage({type:'append',csv:line});"
"}"
"function handleCaptureChunk(csvText){"
"if(!captureActive||!csvText){return;}"
"captureWorker.postMessage({type:'append',csv:csvText});"
"}"
"function buildVerdict(d){"
"if(d.wifi_role==='dedicated_ap'){return 'Dedicated AP mode is running. This board is providing a cleaner Wi-Fi source and periodic broadcast traffic for the sensor ESP32.';}"
"if(d.setup_step){return d.setup_step;}"
"if(d.calibration_guard_blocked&&!d.force_calibration_enabled){return 'Calibration guard blocked baseline learning because the scene looked occupied. Clear the area or enable force calibration if you want to override it.';}"
"if(!d.detection_enabled){return 'Detection is paused. You can capture raw CSI now, then press Start Detection to begin a fresh calibration.';}"
"if(!d.baseline_ready){return 'Baseline is still calibrating. Keep the room empty until calibration reaches 100%.';}"
"if((d.packet_rate_hz||0)<15){return 'Packet rate is low. CSI capture may be limited by AP traffic, geometry, or weak RSSI.';}"
"if((d.motion_score||0)<0.8&&(d.occupancy_score||0)<0.8){return 'Both occupancy and motion scores are weak. Try walking directly across the AP-to-ESP32 path or move the devices farther apart.';}"
"if((d.motion_score||0)>=(d.motion_enter_threshold||0)&&d.presence==='no_presence'){return 'Motion score is strong enough, but the FSM has not promoted state yet. Watch the FSM counters and hold frame values.';}"
"if((d.occupancy_score||0)>=(d.presence_enter_threshold||0)&&d.presence==='no_presence'){return 'Occupancy is elevated, but it is not persisting long enough for static presence confirmation.';}"
"if((d.disturbance_count||0)>0&&d.presence==='no_presence'){return 'The radar is seeing disturbance without sustained occupancy. Periodic motion like fans may be dominating.';}"
"return 'Use the raw energies and thresholds below to compare empty-room, walk-through, and stand-still tests.';"
"}"
"function guidedStageName(stage){"
"const names=['idle','empty_room','walk_test','still_test','clear_test','complete'];"
"return names[Number(stage)||0]||'idle';"
"}"
"function guidedInstruction(d){"
"const stage=Number(d.guided_stage)||0;"
"if(stage===1&&!d.baseline_ready){return 'Keep the sensing area empty while baseline calibration reaches 100%.';}"
"if(stage>0&&stage<5&&!d.guided_sampling){return 'Prepare for this stage, then press Start Sampling when you are ready.';}"
"if(stage===1){return 'Keep the sensing area empty for a few seconds, then press Next Step.';}"
"if(stage===2){return 'Walk across the AP-to-sensor path, then press Next Step.';}"
"if(stage===3){return 'Stand or sit still in the target area, then press Next Step.';}"
"if(stage===4){return 'Leave the sensing area empty again, then press Next Step.';}"
"if(stage===5){return 'Review the measured response and suggested thresholds.';}"
"return d.setup_step||'Start Guided Setup with the sensing area empty.';"
"}"
"function updateGuidedUi(d){"
"const stage=Number(d.guided_stage)||0;"
"const active=!!d.guided_active;"
"const result=d.guided_result||'incomplete';"
"const settling=Math.ceil((Number(d.guided_settle_frames_remaining)||0)/50);"
"const samplingState=d.guided_sampling?'sampling':(stage===0||stage===5?'idle':'waiting');"
"setText('setup-step',guidedInstruction(d));"
"setText('guided-stage-text',guidedStageName(stage));"
"setText('guided-sampling-text',samplingState);"
"setText('guided-samples-text',String(d.guided_stage_samples||0));"
"setText('guided-result-text',result);"
"document.getElementById('guided-result-text').className='diag-v '+((result==='strong'||result==='good')?'quality-good':(result==='fair'?'quality-fair':'quality-poor'));"
"setText('guided-profile-mode-text',d.guided_profile_mode||'incomplete');"
"setText('guided-motion-th-text',fmt(d.guided_suggested_motion_threshold));"
"setText('guided-presence-th-text',fmt(d.guided_suggested_presence_enter));"
"setText('guided-contrast-text',fmt(d.guided_motion_contrast)+' / '+fmt(d.guided_static_contrast));"
"setText('guided-walk-text',fmt(d.guided_walk_motion_peak)+' / '+fmt(d.guided_walk_motion_mean));"
"setText('guided-still-text',fmt(d.guided_still_occupancy_mean)+' / '+fmt(d.guided_still_motion_mean));"
"setText('guided-clear-text',fmt(d.guided_clear_occupancy_mean)+' / '+fmt(d.guided_clear_motion_mean));"
"guidedStartBtn.textContent=(active||stage===5)?'Restart Guided Setup':'Start Guided Setup';"
"guidedStartBtn.className=active?'toggle-on':'primary';"
"guidedSampleBtn.disabled=stage===0||stage===5||d.guided_sampling||!d.baseline_ready;"
"guidedSampleBtn.className=d.guided_sampling?'toggle-on':'secondary';"
"guidedApplyBtn.textContent=d.guided_profile_applied?'Profile Applied':'Apply Suggested Profile';"
"guidedApplyBtn.className=d.guided_profile_applied?'toggle-on':'secondary';"
"guidedNextBtn.disabled=stage===0||stage===5||(!d.baseline_ready&&stage===1);"
"guidedApplyBtn.disabled=!(stage===5&&(d.guided_suggested_motion_threshold||0)>=1);"
"guidedCancelBtn.disabled=stage===0;"
"}"
"function setRangeValue(id,value){"
"const input=document.getElementById(id);"
"const label=document.getElementById(id+'-text');"
"if(!input||value===undefined||value===null){return;}"
"const text=Number(value||0).toFixed(2);"
"input.value=text;"
"if(label){label.textContent=text;}"
"}"
"function addLog(msg){"
"const li=document.createElement('li');"
"li.className='log-item';"
"li.textContent=new Date().toLocaleTimeString()+'  '+msg;"
"logList.prepend(li);"
"while(logList.children.length>8){logList.removeChild(logList.lastChild);}"
"}"
"function applyState(state){"
"const pill=document.getElementById('state-pill');"
"pill.className='pill '+state;"
"document.getElementById('state-text').textContent=state;"
"}"
"function drawWave(values){"
"ctx.clearRect(0,0,wave.width,wave.height);"
"ctx.fillStyle='rgba(87,199,255,0.05)';"
"ctx.fillRect(0,0,wave.width,wave.height);"
"ctx.strokeStyle='rgba(255,255,255,0.08)';"
"for(let i=1;i<4;i++){"
"const y=(wave.height/4)*i;"
"ctx.beginPath();ctx.moveTo(0,y);ctx.lineTo(wave.width,y);ctx.stroke();"
"}"
"if(!values.length){return;}"
"const max=Math.max(...values,1);"
"ctx.lineWidth=2;"
"ctx.strokeStyle='#57c7ff';"
"ctx.beginPath();"
"values.forEach((v,i)=>{"
"const x=(i/(values.length-1||1))*wave.width;"
"const y=wave.height-((v/max)*(wave.height-24))-12;"
"if(i===0){ctx.moveTo(x,y);}else{ctx.lineTo(x,y);}"
"});"
"ctx.stroke();"
"}"
"function sampleWaterfall(values){"
"if(!values.length){return [];}"
"const count=Math.min(WATERFALL_SUBCARRIERS,values.length);"
"const sampled=[];"
"for(let i=0;i<count;i++){"
"const idx=Math.round((i/Math.max(count-1,1))*Math.max(values.length-1,0));"
"sampled.push(Number(values[idx]||0));"
"}"
"return sampled;"
"}"
"function heatColor(v){"
"const t=Math.max(0,Math.min(1,v));"
"if(t<0.25){const p=t/0.25;return 'rgb('+Math.round(6+5*p)+','+Math.round(17+62*p)+','+Math.round(28+80*p)+')';}"
"if(t<0.5){const p=(t-0.25)/0.25;return 'rgb('+Math.round(11+25*p)+','+Math.round(79+114*p)+','+Math.round(108+147*p)+')';}"
"if(t<0.75){const p=(t-0.5)/0.25;return 'rgb('+Math.round(36+219*p)+','+Math.round(193+16*p)+','+Math.round(255-153*p)+')';}"
"const p=(t-0.75)/0.25;return 'rgb(255,'+Math.round(209-102*p)+','+Math.round(102-37*p)+')';"
"}"
"function updateWaterfall(values){"
"const sampled=sampleWaterfall(values);"
"if(!sampled.length){drawWaterfall();return;}"
"const peak=Math.max(...sampled,1);"
"const frame=sampled.map((value,i)=>{"
"const prev=previousWaterfallSample.length===sampled.length?previousWaterfallSample[i]:value;"
"const delta=Math.abs(value-prev);"
"const level=value/peak;"
"const intensity=Math.min(1,(delta/peak)*6+(level*0.18));"
"return intensity;"
"});"
"previousWaterfallSample=sampled.slice();"
"waterfallFrames.push(frame);"
"if(waterfallFrames.length>WATERFALL_HISTORY){waterfallFrames.shift();}"
"drawWaterfall();"
"}"
"function drawWaterfall(){"
"waterfallCtx.clearRect(0,0,waterfall.width,waterfall.height);"
"waterfallCtx.fillStyle='rgba(6,17,28,0.96)';"
"waterfallCtx.fillRect(0,0,waterfall.width,waterfall.height);"
"waterfallCtx.strokeStyle='rgba(255,255,255,0.06)';"
"for(let i=1;i<4;i++){"
"const x=(waterfall.width/4)*i;"
"waterfallCtx.beginPath();waterfallCtx.moveTo(x,0);waterfallCtx.lineTo(x,waterfall.height);waterfallCtx.stroke();"
"}"
"if(!waterfallFrames.length){"
"waterfallCtx.fillStyle='rgba(142,167,191,0.75)';"
"waterfallCtx.font='12px '+getComputedStyle(document.body).fontFamily;"
"waterfallCtx.fillText('Waiting for CSI history...',16,24);"
"return;"
"}"
"const rows=Math.max(...waterfallFrames.map((frame)=>frame.length),1);"
"const cellW=waterfall.width/Math.max(WATERFALL_HISTORY,1);"
"const cellH=waterfall.height/rows;"
"waterfallFrames.forEach((frame,col)=>{"
"frame.forEach((value,row)=>{"
"waterfallCtx.fillStyle=heatColor(value);"
"waterfallCtx.fillRect(col*cellW,waterfall.height-((row+1)*cellH),Math.ceil(cellW)+1,Math.ceil(cellH)+1);"
"});"
"});"
"waterfallCtx.fillStyle='rgba(142,167,191,0.82)';"
"waterfallCtx.font='11px '+getComputedStyle(document.body).fontFamily;"
"waterfallCtx.fillText('subcarriers',12,waterfall.height-12);"
"waterfallCtx.fillText('time',waterfall.width-36,18);"
"}"
"function handleData(d){"
"const quality=d.setup_quality||'poor';"
"const qualityScore=Math.round(d.setup_quality_score||0);"
"const rssiAvg=(d.rssi_avg===undefined||d.rssi_avg<=-126)?'--':fmt(d.rssi_avg);"
"const rssiRange=((d.min_rssi||-127)<=-126||((d.max_rssi||-127)<=-126))?'--':String(d.min_rssi)+'..'+String(d.max_rssi);"
"amps=Array.isArray(d.amplitudes)?d.amplitudes:[];"
"drawWave(amps);"
"updateWaterfall(amps);"
"document.getElementById('wifi-text').textContent=d.wifi_connected?(d.wifi_role==='dedicated_ap'?'ap ready':'online'):(d.wifi_role==='dedicated_ap'?'starting ap':'connecting');"
"document.getElementById('cal-text').textContent=d.wifi_role==='dedicated_ap'?'n/a':(d.detection_enabled?((d.calibration_percent||0)+'%'):'paused');"
"document.getElementById('rssi-text').textContent=((d.last_rssi===undefined||d.last_rssi===null||d.last_rssi<=-120)?'--':d.last_rssi)+' dBm';"
"document.getElementById('ip-text').textContent=d.remote_addr||'0.0.0.0';"
"document.getElementById('event-text').textContent=d.event_count||0;"
"document.getElementById('disturbance-text').textContent=d.disturbance_count||0;"
"document.getElementById('quality-text').textContent=quality;"
"document.getElementById('quality-text').className='side-value quality-'+quality;"
"document.getElementById('occ-text').textContent=fmt(d.occupancy_score);"
"document.getElementById('motion-text').textContent=fmt(d.motion_score);"
"document.getElementById('stability-text').textContent=fmt(d.stability_score);"
"document.getElementById('subcarrier-text').textContent=(d.subcarriers||0)+' active subcarriers';"
"document.getElementById('ts-text').textContent=String(Math.trunc(d.last_timestamp_us||0));"
"document.getElementById('baseline-text').textContent=d.wifi_role==='dedicated_ap'?'n/a':(d.detection_enabled?(d.baseline_ready?'yes':'no'):'paused');"
"document.getElementById('cal-guard-text').textContent=d.force_calibration_enabled?'forced':(d.calibration_guard_blocked?'blocked':'clear');"
"document.getElementById('cal-guard-count').textContent=String(d.calibration_guard_hits||0);"
"document.getElementById('legacy-text').textContent='legacy status: '+(d.status||'waiting');"
"setText('log-client-text',String(d.log_stream_clients||0));"
"setText('ws-log-command','node tools/capture_ws.mjs ws://'+(((d.remote_addr&&d.remote_addr!=='0.0.0.0')?d.remote_addr:location.hostname))+'/ws/log session.csv');"
"updateAnnotationUi(d.manual_annotation);"
"setText('setup-step',d.setup_step||'Start detection with an empty sensing area.');"
"setText('deploy-text',d.deployment_ready?'ready':'not ready');"
"document.getElementById('deploy-text').className='diag-v '+(d.deployment_ready?'quality-good':'quality-fair');"
"setText('quality-score-text',String(qualityScore)+' / 100');"
"document.getElementById('quality-score-text').className='diag-v quality-'+quality;"
"setText('quality-reason-text',d.setup_reason||'waiting');"
"setText('diag-rssi',rssiAvg+' dBm / '+rssiRange);"
"updateGuidedUi(d);"
"setText('diag-rate',fmt(d.packet_rate_hz)+' Hz');"
"setText('diag-jitter',fmt(d.packet_rate_jitter_hz)+' Hz');"
"setText('diag-sc',String(d.valid_subcarriers||0)+' / '+String(d.subcarriers||0));"
"setText('diag-drops',String(d.queue_drop_count||0));"
"setText('diag-occ-raw',fmt(d.occupancy_energy)+' / '+fmt(d.occupancy_ref));"
"setText('diag-motion-avg',fmt(d.motion_avg_energy)+' / '+fmt(d.motion_ref));"
"setText('diag-motion-raw',fmt(d.motion_energy)+' / '+fmt(d.motion_enter_threshold));"
"setText('diag-presence-th',fmt(d.presence_enter_threshold)+' / '+fmt(d.presence_clear_threshold));"
"setText('diag-fsm','M'+String(d.macro_frames||0)+' s'+String(d.static_frames||0)+' c'+String(d.clear_frames||0));"
"setText('diag-hold',String(d.presence_hold_frames||0));"
"setText('diag-frames',String(d.processed_frame_count||0));"
"setText('diag-verdict',buildVerdict(d));"
"motionRange.value=(d.motion_threshold||1.35).toFixed(2);"
"motionRangeText.textContent=(d.motion_threshold||1.35).toFixed(2);"
"setRangeValue('motion-clear-range',d.motion_clear_threshold);"
"setRangeValue('presence-enter-range',d.presence_enter_threshold);"
"setRangeValue('presence-clear-range',d.presence_clear_threshold);"
"notchRange.value=(d.notch_hz||0).toFixed(1);"
"notchRangeText.textContent=(d.notch_hz||0).toFixed(1);"
"loggingBtn.textContent='Serial Logging (debug): '+(d.raw_logging_enabled?'on':'off');"
"loggingBtn.className=d.raw_logging_enabled?'toggle-on':'toggle-off';"
"forceCalibration.checked=!!d.force_calibration_enabled;"
"captureActive=!!d.capture_enabled;"
"updateDetectionUi(!!d.detection_enabled);"
"updateRoleUi(d.wifi_role,d.ap_client_count);"
"updateCaptureUi();"
"const realtimeState=d.presence;"
"if(realtimeState&&realtimeState!==currentState){"
"currentState=realtimeState;"
"applyState(currentState);"
"addLog('realtime -> '+currentState+' | motion='+fmt(d.motion_score));"
"}"
"if(lastEventCount!==-1&&d.event_count>lastEventCount&&d.presence){"
"addLog('presence event confirmed: '+d.presence);"
"}"
"lastEventCount=d.event_count||0;"
"}"
"function connect(){"
"ws=new WebSocket(WS_URL);"
"ws.onopen=()=>{clearTimeout(reconnectTimer);addLog('websocket connected');};"
"ws.onclose=()=>{addLog('websocket reconnecting');reconnectTimer=setTimeout(connect,2000);};"
"ws.onerror=()=>ws.close();"
"ws.onmessage=(e)=>{let msg;try{msg=JSON.parse(e.data);}catch(err){addLog('capture parse warning');return;}if(msg.type==='capture_chunk'){handleCaptureChunk(msg.csv);}else if(msg.type==='capture'){handleCaptureRow(msg.csv);}else{handleData(msg);}};"
"}"
"motionRange.addEventListener('input',()=>{motionRangeText.textContent=Number(motionRange.value).toFixed(2);if(ws&&ws.readyState===1){ws.send(JSON.stringify({cmd:'set_motion_threshold',value:Number(motionRange.value)}));}});"
"profileThresholdRanges.forEach((input)=>{input.addEventListener('input',()=>{const label=document.getElementById(input.id+'-text');const value=Number(input.value);if(label){label.textContent=value.toFixed(2);}if(ws&&ws.readyState===1){ws.send(JSON.stringify({cmd:'set_profile_threshold',name:input.dataset.profileThreshold,value:value}));}});});"
"notchRange.addEventListener('input',()=>{notchRangeText.textContent=Number(notchRange.value).toFixed(1);if(ws&&ws.readyState===1){ws.send(JSON.stringify({cmd:'set_notch',value:Number(notchRange.value)}));}});"
"motionRange.addEventListener('pointerdown',()=>{if(tuningUnlocked){scheduleTuningAutoLock();}});"
"profileThresholdRanges.forEach((input)=>{input.addEventListener('pointerdown',()=>{if(tuningUnlocked){scheduleTuningAutoLock();}});input.addEventListener('change',()=>{if(tuningUnlocked){scheduleTuningAutoLock();}});});"
"notchRange.addEventListener('pointerdown',()=>{if(tuningUnlocked){scheduleTuningAutoLock();}});"
"motionRange.addEventListener('change',()=>{if(tuningUnlocked){scheduleTuningAutoLock();}});"
"notchRange.addEventListener('change',()=>{if(tuningUnlocked){scheduleTuningAutoLock();}});"
"tuneLockBtn.addEventListener('click',()=>{tuningUnlocked=!tuningUnlocked;updateTuneUi();if(tuningUnlocked){scheduleTuningAutoLock();addLog('tuning controls unlocked for 8s');}else{clearTimeout(tuningAutoLockTimer);addLog('tuning controls locked');}});"
"annotationButtons.forEach((btn)=>{btn.addEventListener('click',()=>{const value=btn.dataset.annotation||'none';if(ws&&ws.readyState===1){ws.send(JSON.stringify({cmd:'set_annotation',value:value}));updateAnnotationUi(value);addLog('manual annotation -> '+value);}});});"
"forceCalibration.addEventListener('change',()=>{if(ws&&ws.readyState===1){ws.send(JSON.stringify({cmd:'set_force_calibration',value:forceCalibration.checked}));addLog(forceCalibration.checked?'force calibration enabled':'force calibration disabled');}});"
"document.getElementById('recal-btn').addEventListener('click',()=>{if(ws&&ws.readyState===1){ws.send(JSON.stringify({cmd:'recalibrate'}));addLog('manual recalibration requested');}});"
"detectBtn.addEventListener('click',()=>{if(ws&&ws.readyState===1){const enable=detectBtn.textContent.startsWith('Start');ws.send(JSON.stringify({cmd:'set_detection',value:enable}));addLog(enable?'detection started; calibrating baseline':'detection paused');}});"
"guidedStartBtn.addEventListener('click',()=>{if(ws&&ws.readyState===1){ws.send(JSON.stringify({cmd:'guided_setup_start'}));addLog('guided setup started');}});"
"guidedSampleBtn.addEventListener('click',()=>{if(ws&&ws.readyState===1){ws.send(JSON.stringify({cmd:'guided_setup_start_sampling'}));addLog('guided setup sampling started');}});"
"guidedNextBtn.addEventListener('click',()=>{if(ws&&ws.readyState===1){ws.send(JSON.stringify({cmd:'guided_setup_advance'}));addLog('guided setup advanced');}});"
"guidedApplyBtn.addEventListener('click',()=>{if(ws&&ws.readyState===1){ws.send(JSON.stringify({cmd:'guided_setup_apply_profile'}));addLog('applied suggested detection profile');}});"
"guidedCancelBtn.addEventListener('click',()=>{if(ws&&ws.readyState===1){ws.send(JSON.stringify({cmd:'guided_setup_cancel'}));addLog('guided setup canceled');}});"
"loggingBtn.addEventListener('click',()=>{const enable=!loggingBtn.textContent.endsWith('on');if(ws&&ws.readyState===1){ws.send(JSON.stringify({cmd:'set_logging',value:enable}));}});"
"captureBtn.addEventListener('click',()=>{"
"if(!ws||ws.readyState!==1){addLog('capture requires websocket connection');return;}"
"if(!captureActive){captureRowCount=0;captureWorker.postMessage({type:'reset'});captureActive=true;updateCaptureUi();ws.send(JSON.stringify({cmd:'set_capture',value:true}));addLog('browser capture started');}"
"else{ws.send(JSON.stringify({cmd:'set_capture',value:false}));captureActive=false;updateCaptureUi();addLog('browser capture stopped; downloading csv');downloadCapture();}"
"});"
"applyState(currentState);"
"drawWave([]);"
"drawWaterfall();"
"updateAnnotationUi('none');"
"updateTuneUi();"
"updateDetectionUi(false);"
"updateCaptureUi();"
"addLog('waiting for CSI frames');"
"connect();"
"</script>"
"</body>"
"</html>";
